[versions]
agrona = "2.4.0"
asciidoctorj = "3.0.1"
assertj = "3.27.6"
bouncycastle-prov = "1.83"
caffeine = "3.2.3"
checkStyle = "10.12.1"
commons-io = "2.21.0"
commons-lang3 = "3.20.0"
commons-math3 = "3.6.1"
commons-text = "1.15.0"
compile-testing = "0.23.0"
cypher-dsl = "2021.2.0"
eclipse-collections = "13.0.0"
ejml = "0.44.0"
fastcsv = "4.1.0"
gdl = "0.3.9"
google-auto-common = "1.2.2"
google-auto-service = "1.1.1"
hamcrest = "3.0"
hdrhistogram = "2.2.2"
# @pin - later versions have breaking changes
hppc = "0.7.3"
immutables = "2.12.0"
ipaddress = "5.5.1"
jackson = "2.20.1"
javapoet = "1.13.0"
jetbrains-annotations = "26.0.2-1"
jjwt = "0.13.0"
jol = "0.17"
jqwik = "1.9.3"
junit-pioneer = "2.3.0"
junit5bom = "6.0.1"
log4j = "2.25.3"
memoryfilesystem = "2.8.2"
mockito-junit-jupiter = "5.21.0"
opencypher-front-end = "9.0.20210312"
picocli = "4.7.7"
# @pin - should match the one defined by Neo4j core-db
protobuf = "4.32.1"
qala-datagen = "2.5.1"
# @pin have to figure out what goes wrong when updated
record-builder = "42"
reflections = "0.10.2"
sb-contrib = "7.6.3"
# @pin the scala version should be aligned with the one used by Neo4j?
scala = "2.13.17"
stormpot = "4.1"

[libraries]
agrona = { module = "org.agrona:agrona", version.ref = "agrona" }
asciidoctorj = { module = "org.asciidoctor:asciidoctorj", version.ref = "asciidoctorj" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
bouncycastle-prov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle-prov" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commons-math3" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
eclipse-collections = { module = "org.eclipse.collections:eclipse-collections", version.ref = "eclipse-collections" }
eclipse-collections-api = { module = "org.eclipse.collections:eclipse-collections-api", version.ref = "eclipse-collections" }
ejml-core = { module = "org.ejml:ejml-core", version.ref = "ejml" }
ejml-ddense = { module = "org.ejml:ejml-ddense", version.ref = "ejml" }
fastcsv = { module = "de.siegmar:fastcsv", version.ref = "fastcsv" }
gdl = { module = "com.github.s1ck:gdl", version.ref = "gdl" }
google-auto-common = { module = "com.google.auto:auto-common", version.ref = "google-auto-common" }
google-auto-service = { module = "com.google.auto.service:auto-service", version.ref = "google-auto-service" }
google-testing-compile = { module = "com.google.testing.compile:compile-testing", version.ref = "compile-testing" }
hamcrest = { module = "org.hamcrest:hamcrest-library", version.ref = "hamcrest" }
hdrhistogram = { module = "org.hdrhistogram:HdrHistogram", version.ref = "hdrhistogram" }
hppc = { module = "com.carrotsearch:hppc", version.ref = "hppc" }
immutables-builder = { module = "org.immutables:builder", version.ref = "immutables" }
immutables-value = { module = "org.immutables:value", version.ref = "immutables" }
immutables-value-annotations = { module = "org.immutables:value-annotations", version.ref = "immutables" }
ipaddress = { module = "com.github.seancfoley:ipaddress", version.ref = "ipaddress" }
jackson-annotations = "com.fasterxml.jackson.core:jackson-annotations:2.20"
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-dataformat-csv = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-csv", version.ref = "jackson" }
jackson-datatype = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
jol-core = { module = "org.openjdk.jol:jol-core", version.ref = "jol" }
jqwik = { module = "net.jqwik:jqwik", version.ref = "jqwik" }
junit-pioneer = { module = "org.junit-pioneer:junit-pioneer", version.ref = "junit-pioneer" }
junit5-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit5-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit5-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit5-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit5-migration = { module = "org.junit.jupiter:junit-jupiter-migrationsupport" }
junit5-platform = { module = "org.junit.platform:junit-platform-launcher" }
junit5bom = { module = "org.junit:junit-bom", version.ref = "junit5bom" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
memoryfilesystem = { module = "com.github.marschall:memoryfilesystem", version.ref = "memoryfilesystem" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito-junit-jupiter" }
neo4j-cypher-dsl = { module = "org.neo4j:neo4j-cypher-dsl", version.ref = "cypher-dsl" }
opencypher-astfactory = { module = "org.opencypher:cypher-ast-factory-9.0", version.ref = "opencypher-front-end" }
opencypher-ccparser = { module = "org.opencypher:cypher-javacc-parser-9.0", version.ref = "opencypher-front-end" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
qaladatagen = { module = "io.qala.datagen:qala-datagen-junit5", version.ref = "qala-datagen" }
recordBuilder = { module = "io.soabase.record-builder:record-builder-processor", version.ref = "record-builder" }
reflections = { module = "org.reflections:reflections", version.ref = "reflections" }
scala-library = { module = "org.scala-lang:scala-library", version.ref = "scala" }
stormpot = { module = "com.github.chrisvest:stormpot", version.ref = "stormpot" }

[plugins]
champeau-mrjar = "me.champeau.mrjar:0.1.1"
forbiddenapis = "de.thetaphi.forbiddenapis:3.10"
google-protobuf = "com.google.protobuf:0.9.6"
nebula-basic = "com.netflix.nebula.info-basic:16.0.0"
nebula-broker = "com.netflix.nebula.info-broker:16.0.0"
nebula-dependencies = "com.netflix.nebula.info-dependencies:16.0.0"
nebula-java = "com.netflix.nebula.info-java:16.0.0"
nebula-props = "com.netflix.nebula.info-props:16.0.0"
nebula-scm = "com.netflix.nebula.info-scm:16.0.0"
shadowjar = "com.gradleup.shadow:9.3.1"
spawn = "ch.kk7.spawn:1.0.20180924200750"

[bundles]
test-basic = [
    "assertj-core",
    "junit5-jupiter",
]
test-mocking = [
    "assertj-core",
    "junit5-jupiter",
    "mockito-junit-jupiter",
]
test-platforms = [
    "jqwik",
    "junit5-platform",
]
